# Generated by Django 5.1 on 2024-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=40)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Garments', 'Gaarments'), ('Fintech', 'Fintech')], max_length=80)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
